// <auto-generated />
using HomeLoanapi.Contextt;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeLoanapi.Migrations
{
    [DbContext(typeof(Appdb))]
    [Migration("20230313083420_v3")]
    partial class v3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HomeLoanapi.Models.Application_Form", b =>
                {
                    b.Property<int>("Application_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Aadhar_no")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("NOC")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("SalarySlip")
                        .HasColumnType("tinyint");

                    b.Property<string>("employee_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("organisation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("pan_card")
                        .HasColumnType("tinyint");

                    b.Property<string>("property_location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("property_price")
                        .HasColumnType("float");

                    b.Property<int>("userid")
                        .HasColumnType("int");

                    b.HasKey("Application_id");

                    b.HasIndex("userid");

                    b.ToTable("Applicationform");
                });

            modelBuilder.Entity("HomeLoanapi.Models.Loandetails", b =>
                {
                    b.Property<int>("LoanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Application_Id")
                        .HasColumnType("int");

                    b.Property<float>("EMI")
                        .HasColumnType("real");

                    b.Property<float>("Loan_Amount")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LoanId");

                    b.HasIndex("Application_Id")
                        .IsUnique();

                    b.ToTable("loandetails");
                });

            modelBuilder.Entity("HomeLoanapi.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("HomeLoanapi.Models.Application_Form", b =>
                {
                    b.HasOne("HomeLoanapi.Models.Users", "User")
                        .WithMany("ApplicationForm")
                        .HasForeignKey("userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeLoanapi.Models.Loandetails", b =>
                {
                    b.HasOne("HomeLoanapi.Models.Application_Form", "ApplicationForm")
                        .WithOne("details")
                        .HasForeignKey("HomeLoanapi.Models.Loandetails", "Application_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApplicationForm");
                });

            modelBuilder.Entity("HomeLoanapi.Models.Application_Form", b =>
                {
                    b.Navigation("details");
                });

            modelBuilder.Entity("HomeLoanapi.Models.Users", b =>
                {
                    b.Navigation("ApplicationForm");
                });
#pragma warning restore 612, 618
        }
    }
}
